### ISSUE TITLE
Not working over hotspot

### ISSUE THREAD

**Issue by Gibbz** [williamMillington/warpinator-iOS#3]
I'd like to use hotspot on either iPhone or Android. Then use warpinator to send files. I've done this on android before, but with the iPhone version this does not work.
Any ideas?

**Comment by williamMillington** [comment]
Hello!

If you are talking about using the same iphone/android to create the hotspot AND share files, then I'm not sure if that is possible.  My current understanding is that a device cannot use its own hotspot because it's wifi module is basically pretending to be a router (sending all traffic –both that of your phone and anyone connected to the hotspot– through the phone's cellular connection), and will operate only in that capacity until the hotspot is turned off.  However, this may have changed with the MIMO being built into everything; I'll look into it!

If you're talking about wanting to use one device to create a hotspot (say, an android), and then use that hotspot to share files between two other devices (ex. iphone and linux) –and WarpinatoriOS isn't letting you do that– then that would be more in "bug" territory and I'll investigate accordingly. There may be some technical reason why hotspots don't support mDNS, or perhaps need to be specially configured to do so.

Thanks for the feedback!

**Comment by Gibbz** [comment]
No worries. I created a hotspot on one phone, then connected the other to it. It didn't work, but seemed to briefly show the other phone. So from that assumed it should work. Otherwise you can close the bug :)
